# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: pmd

on:
  #push:
  #  branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    
permissions:
  contents: read

jobs:
  pmd-code-scan:
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

       # Install missing maven dependencies

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'


      - name: List jar Directories
        run: |
            find . -type d -name "install" | grep -v "/\." | sed 's|^./||'
            
      - name: Install Dependencies
        run: |
          chmod +x ./install/install.sh
          mvn install:install-file -DgroupId=wsdbench-component -DartifactId=wsdbench-component -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true -Dfile=wsdbench-component.jar
          mvn install:install-file -DgroupId=wsdbench-distributable-objects -DartifactId=wsdbench-distributable-objects -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true -Dfile=wsdbench-distributable-objects.jar
          mvn install:install-file -DgroupId=wsdbench-loader -DartifactId=wsdbench-loader -Dversion=1.0 -Dpackaging=jar -DgeneratePom=true -Dfile=wsdbench-loader.jar
          mvn install:install-file -DgroupId=oracle -DartifactId=ojdbc14 -Dversion=1.0 -Dpackaging=jar -Dfile=ojdbc14.jar -DgeneratePom=true         
         # ./install/install.sh
    
      - name: Build project
        run: mvn clean install -Dmaven.test.skip=true

      - name: List Target Directories
        run: |
            find . -type d -name "target" | grep -v "/\." | sed 's|^./||'
      - name: List Source Directories
        run: |
          find . -type d -name "src" | grep -v "/\." | sed 's|^./||'
          
      - name: Run PMD
        id: pmd
        uses: pmd/pmd-github-action@v2
        with:
          rulesets: 'rulesets/java/quickstart.xml'
          analyzeModifiedFilesOnly: false
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: pmd-report.sarif

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }} 
        with:
          args: 
            -Dsonar.projectKey=${{ secrets.WSVD_SONAR_PROJECT_KEY }}  
            -Dsonar.java.binaries="target"
