# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: semgrep

on:
  #push:
  #  branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    
permissions:
  contents: read

jobs:
  pmd-code-scan:
    permissions:
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    steps:
      - uses: actions/checkout@v3

      # step 2
      - name: Semgrep Scan
        run: |
          semgrep \
            --sarif --output semgrep-report.sarif \
            --metrics=off \
            --config="p/default"

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: semgrep-report.sarif

      - name: Upload Semgrep report
        uses: actions/upload-artifact@v2
        with:
          sarif_file: semgrep-report.sarif
    

